### ISSUE TITLE
do not know the key '/tikz/on grid'

### ISSUE THREAD

**Issue by sunmy2019** [paolobrasolin/kodi#31]
When using `\begin{codi}[tetragonal]` , I got an error.

>  ! Package pgfkeys Error: I do not know the key '/tikz/on grid' and I am going to ignore it. Perhaps you misspelled it.

**I added `\usetikzlibrary[positioning]` in the preamble and fixed it.**

I am using XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-03>
And pgf version 3.1.5b and all packages up to date

**Comment by paolobrasolin** [comment]
Thanks for both the bug report and the fix @sunmy2019!

I just cut [1.0.1](https://github.com/paolobrasolin/commutative-diagrams/releases/tag/v1.0.1) to fix this. It'll soon be available on CTAN too. 🚀
