### ISSUE TITLE
How are nodes containing macros named?

### ISSUE THREAD

**Issue by I0amLK** [paolobrasolin/kodi#39]
I am currently using the CoDi package to create commutative diagrams in LaTeX and I encountered an issue that I hope you could help me with.

Here is the minimal example to reproduce the problem:

```latex
\begin{codi}
    \obj { A_{\mathbb C} & B \\ };
    \mor A_{\mathbb C} f:-> B;
\end{codi}

**Comment by paolobrasolin** [comment]
Hi @I0amLK! Thanks for using CoDi and sorry for the delay.

The mechanism that automatically names nodes drops the special `\` character, so you should drop it when referring to the nodes.

Here's a working example:

```latex
\documentclass[margin=.5cm]{standalone}
\usepackage{commutative-diagrams}
\usepackage{amsfonts}

\begin{document}

\begin{codi}[prompter]
    \obj { A_{\mathbb C} & B \\ };
    \mor A_{mathbb C} f:-> B;
\end{codi}

\end{document}
```

The `prompter` option decorates nodes with their names, so it's useful when you're unsure about automatically generated names:
![image](https://github.com/paolobrasolin/commutative-diagrams/assets/2499655/53fbaff1-b211-4395-8c92-b5335adb5d9f)
