### ISSUE TITLE
Warnings concerning "Missing character: There is no * in font nullfont!" when naming an object

### ISSUE THREAD

**Issue by Holiverse** [paolobrasolin/kodi#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When using the lateste version of Co-Di. Similar to the #42 , if we name objects, there are also some extra warnings.

For example

```
\documentclass[10pt]{article}

\usepackage{commutative-diagrams} 

\begin{document}

\title{Test}
\maketitle


\begin{codi}
    \obj{
                |(C)|C & |(Z)|Z(M)\\
                & |(M)|M\\
            };
    \mor[swap]: C F:-> M;
    \mor: * "F'":-> Z "Forg":-> *; 
\end{codi}

\end{document}
```
I believe this issue is similar to #42 and the number of warnings is much less than before.

**Comment by paolobrasolin** [comment]
Thanks for spotting this @Holiverse!

I fixed three sources of pollution for the logs:
* 689e6377656266b379fe8f3b57ce693caa43ed31 fixes `Missing character: There is no * in font nullfont!` for characters in the node names of `\obj` (this is the one you are pointing to above);
* c5af72407237b146299e5ee8c24e8ec37cb0f5b6 fixes `Missing character: There is no ; in font nullfont!` produced by `\mor`;
* 6729ffd5447ea9b5e114ce786ec9102f9093bd7f fixes Streaks of "ABYN" generated by `\mor` when using the matrix syntax.

Logs should be clean now.

These fixes are included in v1.1.2, just released, available [here](https://github.com/paolobrasolin/commutative-diagrams/releases/tag/v1.1.2) and soon on CTAN.
